m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy)

m1<-formula(newDistBelowOneKm~fac_owned_govt+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_staffQualified+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_medicineavailable+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Less_costly+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Goodstaffattitude+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Wasreferred+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Lesswaitingtime+Diabetes)

m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+Malaria_fever)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+respiratory_pneumonia)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+normal_delivery)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+Accidents_and_injuries)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+Hypertension)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+Diarrhoea)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+caesarean)
m1<-formula(newDistBelowOneKm~fac_owned_govt+reason_Moreprivacy+Diabetes)

